export { default as Follower } from './Follower/Follower';
export { default as HeaderTitle } from './HeaderTitle/HeaderTitle';
export { default as Info } from './Info/Info';
export { default as Likes } from './Info/Likes';
export { default as ToggleButton } from './ToggleButton/ToggleButton';
export { default as TopBg } from './TopBg/TopBg';
export { default as Card } from './UI/Card/Card';
export { default as OverviewItem } from './OverviewItem/OverviewItem';
export { default as ChangeNum } from './ChangeNum/ChangeNum';
